server:
  port: 8080

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: movecall
          uri: http://localhost:8081
          predicates:
            - Path=/movers/**
        - id: movemanage
          uri: http://localhost:8082
          predicates:
            - Path=/movermanages/**
        - id: customer
          uri: http://localhost:8083
          predicates:
            - Path= /moverinfos/**
        - id: moveassign
          uri: http://localhost:8084
          predicates:
            - Path=/moverassigns/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: movecall
          uri: http://localhost:8080
          predicates:
            - Path=/movers/**
        - id: movemanage
          uri: http://localhost:8080
          predicates:
            - Path=/movermanages/**
        - id: customer
          uri: http://localhost:8080
          predicates:
            - Path= /moverinfos/**
        - id: moveassign
          uri: http://localhost:8080
          predicates:
            - Path=/moverassigns/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
